jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-20.04'
  steps:
  - bash: sudo apt-get update; sudo apt-get install -y sysbench
    displayName: Install sysbench
  - bash: bench.sh
    displayName: Run benchmarks
